services:
  - type: web
    name: payfinder-app
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: python backend/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
